# -*- coding: utf-8 -*-
"""Strukdat mini project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gmrwjdauTyQJDUtp9ZDDXP9IKHQRhLmV
"""

!pip install biopython matplotlib pandas
from Bio import SeqIO
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import files
uploaded = files.upload()

file_path = "/content/rcsb_pdb_5FSG.fasta"
sequences = list(SeqIO.parse(file_path, "fasta"))

# 1. Baca file FASTA (hasil upload)
file_path = "/content/rcsb_pdb_5FSG.fasta"
sequences = list(SeqIO.parse(file_path, "fasta"))

# 2. Simpan data dalam List
seq_list = [str(record.seq) for record in sequences]

# 3. Hitung frekuensi nukleotida
def nucleotide_frequency(seq):
    freq = {"A":0, "T":0, "G":0, "C":0}
    for base in seq:
        if base in freq:
            freq[base] += 1
    return freq

freqs = [nucleotide_frequency(seq) for seq in seq_list]

# 4. Hitung GC Content
def gc_content(seq):
    g = seq.count("G")
    c = seq.count("C")
    return (g+c)/len(seq) * 100 if len(seq) > 0 else 0

gc_values = [gc_content(seq) for seq in seq_list]

# 5. Urutkan sekuens berdasarkan GC Content
sorted_indices = sorted(range(len(gc_values)), key=lambda i: gc_values[i], reverse=True)

# 6. Ambil 3 sekuens terbaik
top3_indices = sorted_indices[:3]
top3_seqs = [(sequences[i].id, gc_values[i], seq_list[i]) for i in top3_indices]

print("Top 3 sekuens berdasarkan GC Content:")
for sid, gc, seq in top3_seqs:
    print(f"ID: {sid}, GC Content: {gc:.2f}%")

# 7. Visualisasi grafik GC Content
plt.figure(figsize=(10,6))
plt.bar(range(len(gc_values)), gc_values, color="skyblue")
plt.xlabel("Index Sequences")
plt.ylabel("GC Content (%)")
plt.title("GC Content Hantaan Virus (PDB 5FSG)")
plt.show()

# 8. Simpan hasil ke CSV
df = pd.DataFrame({
    "ID": [record.id for record in sequences],
    "Sequence": seq_list,
    "GC_Content": gc_values
})
df.to_csv("/content/hantaan_gc_content.csv", index=False)
print("Hasil disimpan ke hantaan_gc_content.csv")
files.download("/content/hantaan_gc_content.csv")

import matplotlib.pyplot as plt
import pandas as pd
from Bio import SeqIO
from google.colab import files

# 1. Baca file FASTA
file_path = "/content/rcsb_pdb_5FSG.fasta"
sequences = list(SeqIO.parse(file_path, "fasta"))

# 2. Simpan data dalam List
seq_list = [str(record.seq) for record in sequences]

# 3. Hitung frekuensi nukleotida
def nucleotide_frequency(seq):
    freq = {"A":0, "T":0, "G":0, "C":0}
    for base in seq:
        if base in freq:
            freq[base] += 1
    return freq

freqs = [nucleotide_frequency(seq) for seq in seq_list]

# 4. Hitung GC Content
def gc_content(seq):
    g = seq.count("G")
    c = seq.count("C")
    return (g+c)/len(seq) * 100 if len(seq) > 0 else 0

gc_values = [gc_content(seq) for seq in seq_list]

# 5. Urutkan sekuens berdasarkan GC Content
sorted_indices = sorted(range(len(gc_values)), key=lambda i: gc_values[i], reverse=True)

# 6. Ambil 3 sekuens terbaik
top3_indices = sorted_indices[:3]
top3_seqs = [(sequences[i].id, gc_values[i]) for i in top3_indices]

print("Top 3 sekuens berdasarkan GC Content:")
for sid, gc in top3_seqs:
    print(f"ID: {sid}, GC Content: {gc:.2f}%")

# 7. Visualisasi distribusi GC Content (Histogram)
plt.figure(figsize=(10,6))
plt.hist(gc_values, bins=10, color="skyblue", edgecolor="black")
plt.xlabel("GC Content (%)")
plt.ylabel("Jumlah Sequences")
plt.title("Distribusi GC Content Hantaan Virus (PDB 5FSG)")
plt.show()

# 8. Simpan hasil ke CSV dan langsung download
df = pd.DataFrame({
    "ID": [record.id for record in sequences],
    "GC_Content (%)": gc_values
})
csv_path = "/content/hantaan_gc_content.csv"
df.to_csv(csv_path, index=False)

print("CSV berhasil dibuat dan siap diunduh:", csv_path)
files.download(csv_path)

#List
seq_list = [str(record.seq) for record in sequences]

print(seq_list)